server:
  port: 8501
spring:
  application:
    name: spring-cloud-consul-product-service
  cloud:
    consul:
      discovery:
        serviceName: producer-product-service
        enabled: true
      host: localhost
      port: 8500